// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WindVane.PiliPala.Infrastructure;

namespace WindVane.PiliPala.Infrastructure.Migrations
{
    [DbContext(typeof(PiliPalaDbContext))]
    [Migration("20191027042546_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WindVane.PiliPala.Domain.Models.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("59340fa4-5cf3-4c23-bc1c-62afdb7f530f"),
                            Description = "",
                            DisplayOrder = 100,
                            Icon = "",
                            IsPublished = true,
                            Link = "",
                            Name = "动漫"
                        },
                        new
                        {
                            Id = new Guid("6e661f46-6936-4f94-aa16-3941e0933791"),
                            Description = "",
                            DisplayOrder = 200,
                            Icon = "",
                            IsPublished = true,
                            Link = "",
                            Name = "电影"
                        },
                        new
                        {
                            Id = new Guid("5f5ee2d1-f8b2-47c8-9a03-93cbcedb483b"),
                            Description = "",
                            DisplayOrder = 300,
                            Icon = "",
                            IsPublished = true,
                            Link = "",
                            Name = "电视剧"
                        },
                        new
                        {
                            Id = new Guid("4574a54a-10ba-44cd-8e8d-29e0dd75fe90"),
                            Description = "",
                            DisplayOrder = 400,
                            Icon = "",
                            IsPublished = true,
                            Link = "",
                            Name = "纪录片"
                        },
                        new
                        {
                            Id = new Guid("efd186cc-8e9b-4a13-80d8-b8c6d22ebf37"),
                            Description = "",
                            DisplayOrder = 500,
                            Icon = "",
                            IsPublished = true,
                            Link = "",
                            Name = "体育"
                        },
                        new
                        {
                            Id = new Guid("fff0c016-5101-4a40-94e0-2cc1e09f05cb"),
                            Description = "",
                            DisplayOrder = 600,
                            Icon = "",
                            IsPublished = true,
                            Link = "",
                            Name = "军事"
                        },
                        new
                        {
                            Id = new Guid("546f0c89-19a5-4416-81bb-19498d2e9d73"),
                            Description = "",
                            DisplayOrder = 700,
                            Icon = "",
                            IsPublished = true,
                            Link = "",
                            Name = "历史"
                        },
                        new
                        {
                            Id = new Guid("58dc7967-6c87-46e9-a69c-eaedf4313d0c"),
                            Description = "",
                            DisplayOrder = 800,
                            Icon = "",
                            IsPublished = true,
                            Link = "",
                            Name = "科技"
                        },
                        new
                        {
                            Id = new Guid("e7dffac5-9af4-475b-b3e1-370827b851c9"),
                            Description = "",
                            DisplayOrder = 900,
                            Icon = "",
                            IsPublished = true,
                            Link = "",
                            Name = "编程"
                        },
                        new
                        {
                            Id = new Guid("9de3c6c7-3dab-4e3e-8a75-fdbb213f6644"),
                            Description = "",
                            DisplayOrder = 1000,
                            Icon = "",
                            IsPublished = true,
                            Link = "",
                            Name = "游戏"
                        },
                        new
                        {
                            Id = new Guid("3151a9ed-46fb-4111-9f8d-eb55deb65683"),
                            Description = "",
                            DisplayOrder = 1100,
                            Icon = "",
                            IsPublished = true,
                            Link = "",
                            Name = "原创"
                        },
                        new
                        {
                            Id = new Guid("47b055cd-1ae4-43b8-a730-b0a208e3e076"),
                            Description = "",
                            DisplayOrder = 1200,
                            Icon = "",
                            IsPublished = true,
                            Link = "",
                            Name = "教育"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
