// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WindVane.PiliPala.Infrastructure;

namespace WindVane.PiliPala.Infrastructure.Migrations
{
    [DbContext(typeof(PiliPalaDbContext))]
    [Migration("20191030064406_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WindVane.PiliPala.Domain.Models.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b9414515-f75e-4aa2-a2c2-eac2e0cdc706"),
                            Created = new DateTime(2019, 10, 30, 14, 44, 6, 520, DateTimeKind.Local).AddTicks(5223),
                            Description = "",
                            DisplayOrder = 100,
                            Icon = "",
                            IsPublished = true,
                            Link = "/Channel/Anime",
                            Name = "动漫"
                        },
                        new
                        {
                            Id = new Guid("898365a3-88c3-4a4f-94b9-a5c3f220ed0b"),
                            Created = new DateTime(2019, 10, 30, 14, 44, 6, 521, DateTimeKind.Local).AddTicks(4847),
                            Description = "",
                            DisplayOrder = 200,
                            Icon = "",
                            IsPublished = true,
                            Link = "/Channel/Film",
                            Name = "电影"
                        },
                        new
                        {
                            Id = new Guid("d8abeb69-df56-42b6-9c12-e16274c5baea"),
                            Created = new DateTime(2019, 10, 30, 14, 44, 6, 521, DateTimeKind.Local).AddTicks(4929),
                            Description = "",
                            DisplayOrder = 300,
                            Icon = "",
                            IsPublished = true,
                            Link = "/Channel/TV",
                            Name = "电视剧"
                        },
                        new
                        {
                            Id = new Guid("2c38f9bd-8603-42ca-8707-8a9ab7b4e945"),
                            Created = new DateTime(2019, 10, 30, 14, 44, 6, 521, DateTimeKind.Local).AddTicks(4934),
                            Description = "",
                            DisplayOrder = 400,
                            Icon = "",
                            IsPublished = true,
                            Link = "/Channel/Documentary",
                            Name = "纪录片"
                        },
                        new
                        {
                            Id = new Guid("6ab37c0e-7a63-4f88-8ba6-8ed411436ea4"),
                            Created = new DateTime(2019, 10, 30, 14, 44, 6, 521, DateTimeKind.Local).AddTicks(4936),
                            Description = "",
                            DisplayOrder = 500,
                            Icon = "",
                            IsPublished = true,
                            Link = "/Channel/PhysicalEducation",
                            Name = "体育"
                        },
                        new
                        {
                            Id = new Guid("4174ef5c-b5ac-4b09-9169-4cc507c43720"),
                            Created = new DateTime(2019, 10, 30, 14, 44, 6, 521, DateTimeKind.Local).AddTicks(4938),
                            Description = "",
                            DisplayOrder = 600,
                            Icon = "",
                            IsPublished = true,
                            Link = "/Channel/Military",
                            Name = "军事"
                        },
                        new
                        {
                            Id = new Guid("9a301aca-3d51-430c-bbc7-50353fba98fe"),
                            Created = new DateTime(2019, 10, 30, 14, 44, 6, 521, DateTimeKind.Local).AddTicks(4953),
                            Description = "",
                            DisplayOrder = 700,
                            Icon = "",
                            IsPublished = true,
                            Link = "/Channel/History",
                            Name = "历史"
                        },
                        new
                        {
                            Id = new Guid("b43c0f7b-f074-439d-bb3b-31fc48442924"),
                            Created = new DateTime(2019, 10, 30, 14, 44, 6, 521, DateTimeKind.Local).AddTicks(4955),
                            Description = "",
                            DisplayOrder = 800,
                            Icon = "",
                            IsPublished = true,
                            Link = "/Channel/Technology",
                            Name = "科技"
                        },
                        new
                        {
                            Id = new Guid("2a37341f-1280-40b9-a51f-fb567e3a843a"),
                            Created = new DateTime(2019, 10, 30, 14, 44, 6, 521, DateTimeKind.Local).AddTicks(4957),
                            Description = "",
                            DisplayOrder = 900,
                            Icon = "",
                            IsPublished = true,
                            Link = "/Channel/Program",
                            Name = "编程"
                        },
                        new
                        {
                            Id = new Guid("82ee39df-d97a-4989-af61-f1c71d4ebf6f"),
                            Created = new DateTime(2019, 10, 30, 14, 44, 6, 521, DateTimeKind.Local).AddTicks(4959),
                            Description = "",
                            DisplayOrder = 1000,
                            Icon = "",
                            IsPublished = true,
                            Link = "/Channel/Game",
                            Name = "游戏"
                        },
                        new
                        {
                            Id = new Guid("f8081e01-e924-4a2f-8c22-2e0660416ae3"),
                            Created = new DateTime(2019, 10, 30, 14, 44, 6, 521, DateTimeKind.Local).AddTicks(4962),
                            Description = "",
                            DisplayOrder = 1100,
                            Icon = "",
                            IsPublished = true,
                            Link = "/Channel/Original",
                            Name = "原创"
                        },
                        new
                        {
                            Id = new Guid("4b743707-c824-418e-a2eb-eb5e839b0502"),
                            Created = new DateTime(2019, 10, 30, 14, 44, 6, 521, DateTimeKind.Local).AddTicks(4964),
                            Description = "",
                            DisplayOrder = 1200,
                            Icon = "",
                            IsPublished = true,
                            Link = "/Channel/Education",
                            Name = "教育"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
